spring.application.name=admin-service
server.port=9091
spring.datasource.url=jdbc:postgresql://localhost:5432/certif_db
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret
jwt.secret=9a615631cd197629b35bc20c586111f185799c96191c96443685c7031201047d
jwt.expiration=86400000

# Multipart configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
# Error handling
server.error.include-message=always

# ==========================================
# EMAIL / SMTP CONFIG (Password Reset OTP)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anaskhaiy7@gmail.com
spring.mail.password=tcklxykpgqyffalj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
